/* DO NOT EDIT - Generated by SysConfig for LP_MSPM0G3507, modified for custom board */
#ifndef ti_msp_dl_config_h
#define ti_msp_dl_config_h

#if defined(__ti_version__) || defined(__TI_COMPILER_VERSION__)
#define SYSCONFIG_WEAK __attribute__((weak))
#elif defined(__IAR_SYSTEMS_ICC__)
#define SYSCONFIG_WEAK __weak
#elif defined(__GNUC__)
#define SYSCONFIG_WEAK __attribute__((weak))
#endif

#include <ti/devices/msp/msp.h>
#include <ti/driverlib/driverlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#define POWER_STARTUP_DELAY  (16)
#define CPUCLK_FREQ         32000000

#define ADC12_0_INST        ADC0
#define GRAY_ADC_INST       ADC0
#define GRAY_ADCMEM_0       DL_ADC12_MEM_IDX_0
#define MOTOR_TIM_INST      TIMA0
#define OLED_I2C_INST       I2C1
#define UART_INST           UART1

void SYSCFG_DL_init(void);
void SYSCFG_DL_initPower(void);
void SYSCFG_DL_GPIO_init(void);
void SYSCFG_DL_SYSCTL_init(void);
void SYSCFG_DL_ADC12_0_init(void);
void SYSCFG_DL_TIMER_init(void);
void SYSCFG_DL_I2C_init(void);
void SYSCFG_DL_UART_init(void);

#ifdef __cplusplus
}
#endif
#endif
